version: "3.8"

services:
  app:
    build: .
    restart: unless-stopped
    container_name: app
    ports:
      - 8000:8000
    volumes:
      - ./logs:/app/logs # Example volume for logs - mount this into promtail
    networks:
      example-network:
        ipv4_address: 172.16.238.10

  prometheus:
    image: prom/prometheus:latest
    restart: unless-stopped
    container_name: prometheus
    ports:
      - 9090:9090
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
    command:
      - "--config.file=/etc/prometheus/prometheus.yml"
    networks:
      example-network:
        ipv4_address: 172.16.238.11

  grafana:
    image: grafana/grafana:latest
    restart: unless-stopped
    user: "472"
    container_name: grafana
    depends_on:
      - prometheus
    ports:
      - 3000:3000
    volumes:
      - ./datasource.yml:/etc/grafana/provisioning/datasource.yml
    env_file:
      - ./config.monitoring
    networks:
      example-network:
        ipv4_address: 172.16.238.12

  loki:
    image: grafana/loki:2.3.0
    ports:
      - "3100:3100"
    command: -config.file=/etc/loki/local-config.yaml
    networks:
      example-network:
        ipv4_address: 172.16.238.13

  promtail:
    image: grafana/promtail:2.3.0
    volumes:
      - ./logs:/var/log
    command: -config.file=/etc/promtail/config.yml
    networks:
      example-network:
        ipv4_address: 172.16.238.14

networks:
  example-network:
    name: example-network
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 172.16.238.0/24
